# Generated by Django 4.1.6 on 2023-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='-', upload_to='store/images'),
            preserve_default=False,
        ),
    ]
